import type { RuntimeConfig } from "../config.js";
import type { RuntimeLogger } from "../logger.js";
import type { RedisCoordinator } from "../redis/coordination.js";
import type { RuntimeSettingsService } from "../runtime-settings/service.js";
import type { StorageVnextAuditPort } from "../storage-vnext/audit/ports.js";
import type { StorageVnextAdminReadApplication } from "../storage-vnext/api/admin-read-application.js";
import type { PublicOpenApiKeyRepository } from "../public-openapi/keys.js";
import type { StorageVnextAdminProcessingApplication } from "../storage-vnext/api/admin-processing-application.js";
import type { StorageVnextCatalogReadPort } from "../storage-vnext/catalog/ports.js";
import type { createStorageVnextMaintenanceRequestService } from "../storage-vnext/maintenance/maintenance-coordinator.js";
import type { StorageVnextMaintenanceRepository } from "../storage-vnext/maintenance/ports.js";
import type { StorageVnextAdminSourceApplication } from "../storage-vnext/api/admin-source-application.js";
import type { StorageVnextAdminUploadApplication } from "../storage-vnext/api/admin-upload-application.js";
import type { StorageVnextAdminMutationApplication } from "../storage-vnext/api/admin-mutation-application.js";
import type { StorageVnextAdminCoreApplication } from "../storage-vnext/api/admin-core-application.js";
import type { StorageVnextAdminMaintenanceApplication } from "../storage-vnext/api/admin-maintenance-application.js";
import type { DeveloperOpenApiApplication } from "../storage-vnext/api/openapi-application.js";

export type ApiAppOptions = {
  config: RuntimeConfig;
  redis?: RedisCoordinator;
  runtimeSettings?: RuntimeSettingsService;
  logger?: RuntimeLogger;
  storageVnextAudit?: Pick<StorageVnextAuditPort, "append">;
  storageVnextAdminRead?: StorageVnextAdminReadApplication;
  storageVnextApiKeys?: PublicOpenApiKeyRepository;
  storageVnextAdminProcessing?: StorageVnextAdminProcessingApplication;
  storageVnextCatalog?: StorageVnextCatalogReadPort;
  storageVnextMaintenanceRequests?: ReturnType<typeof createStorageVnextMaintenanceRequestService>;
  storageVnextMaintenanceStatus?: Pick<StorageVnextMaintenanceRepository, "getStatus">;
  storageVnextAdminSource?: StorageVnextAdminSourceApplication;
  storageVnextAdminUpload?: StorageVnextAdminUploadApplication;
  storageVnextAdminMutation?: StorageVnextAdminMutationApplication;
  storageVnextAdminCore?: StorageVnextAdminCoreApplication;
  storageVnextAdminMaintenance?: StorageVnextAdminMaintenanceApplication;
  storageVnextOpenApi?: DeveloperOpenApiApplication;
};
