export const GRAPH_COMMON_TERM_ABSOLUTE_MAX_DOCUMENTS = 64;
export const GRAPH_COMMON_TERM_MAX_DOCUMENT_RATIO = 0.2;
export const GRAPH_QUERY_TERM_LIMIT = 100;
export const GRAPH_LEXICAL_QUERY_TERM_LIMIT = 4;
